import type { TaxonNodeSeed } from "./types.js";

/*
 * 邻接表结构：每个节点只保存 parent_slug。
 * 新增节点时只需在数组中加入一个对象，前端会自动计算层级、祖先链与后代分支。
 */
export const taxonNodes: TaxonNodeSeed[] = [
  {
    slug: "luca",
    parentSlug: null,
    name: "最终共同祖先",
    latin: "LUCA",
    rank: "共同祖先",
    kind: "clade",
    nodeOrder: 1,
    divergenceMya: 3800,
    eraSlug: "archean",
    icon: "orbit",
    color: "#9fe8c8",
    traits: "以 DNA 储存遗传信息；使用共同遗传密码；依赖细胞膜与 ATP 维持生命活动。",
    description: "LUCA（Last Universal Common Ancestor）不是某一个具体物种，而是所有现存生物可以追溯到的最近共同祖先。今天的细菌、古菌与真核生物都从这条演化支分叉而来。",
    relationships: "向下分为细菌与古菌—真核生物两大方向。真核细胞后来通过内共生获得线粒体，开启复杂生命的可能。",
    defaultExpanded: true
  },
  {
    slug: "bacteria",
    parentSlug: "luca",
    name: "细菌",
    latin: "Bacteria",
    rank: "域",
    kind: "clade",
    nodeOrder: 1,
    divergenceMya: 3500,
    eraSlug: "archean",
    icon: "layers",
    color: "#86e6bc",
    traits: "原核细胞；无细胞核；多数以二分裂繁殖；代谢方式极其多样。",
    description: "细菌是地球上最早成功扩散的细胞生命之一，能在海洋、土壤、热泉和其他生物体内生活。蓝藻属于这一分支。",
    relationships: "蓝藻等光合细菌改变了大气氧含量，也为后来真核生物的叶绿体祖先提供了来源。",
    defaultExpanded: false
  },
  {
    slug: "cyanobacteria",
    parentSlug: "bacteria",
    name: "蓝藻与叠层石",
    latin: "Cyanobacteria",
    rank: "门",
    kind: "species",
    nodeOrder: 1,
    divergenceMya: 3500,
    eraSlug: "archean",
    organismSlug: "cyanobacteria",
    icon: "layers",
    color: "#86e6bc",
    traits: "产氧光合作用；形成叠层石；可固定大气氮；改变早期地球大气。",
    description: "蓝藻在浅海中捕获矿物质形成层状叠层石，并释放氧气。大氧化事件让厌氧生态系统重组，也为复杂有氧生命创造条件。",
    relationships: "属于细菌分支，是改变地球环境的关键类群；其光合内共生体后来演化为真核藻类和植物的叶绿体。",
    defaultExpanded: false
  },
  {
    slug: "asgard-archaea",
    parentSlug: "luca",
    name: "阿斯加德古菌类群",
    latin: "Asgardarchaeota",
    rank: "超门",
    kind: "clade",
    nodeOrder: 2,
    divergenceMya: 2200,
    eraSlug: "proterozoic",
    icon: "circle-dot",
    color: "#b7d8a7",
    traits: "古菌型细胞膜与信息处理系统，同时拥有若干曾被认为只属于真核细胞的基因。",
    description: "阿斯加德古菌展示了古菌与真核生物之间的深层联系，帮助科学家理解复杂细胞出现前的中间状态。",
    relationships: "与真核生物亲缘关系密切。内共生理论认为，类似古菌的宿主细胞吞噬细菌后形成线粒体。",
    defaultExpanded: false
  },
  {
    slug: "eukaryota",
    parentSlug: "asgard-archaea",
    name: "真核生物",
    latin: "Eukaryota",
    rank: "域",
    kind: "clade",
    nodeOrder: 1,
    divergenceMya: 1800,
    eraSlug: "proterozoic",
    icon: "circle-dot",
    color: "#a7e4d0",
    traits: "具有细胞核、线粒体或其退化结构、内膜系统；可形成大型多细胞身体。",
    description: "真核细胞的出现是复杂生命的重要门槛。细胞核保护基因组，线粒体提供高能量，细胞也能发展出更多专门化结构。",
    relationships: "由古菌样宿主与细菌样线粒体祖先合并形成，后来分化为植物、真菌、动物及众多原生生物。",
    defaultExpanded: true
  },
  {
    slug: "eukaryote",
    parentSlug: "eukaryota",
    name: "原始真核生物",
    latin: "Eukaryota",
    rank: "基干支系",
    kind: "species",
    nodeOrder: 1,
    divergenceMya: 1800,
    eraSlug: "proterozoic",
    organismSlug: "eukaryote",
    icon: "circle-dot",
    color: "#a7e4d0",
    traits: "细胞核；线粒体内共生；较复杂的细胞骨架；具备有丝分裂基础。",
    description: "最早的真核生物可能是单细胞浮游生物。内共生带来的能量效率让更大细胞、更复杂基因组和多细胞演化成为可能。",
    relationships: "位于植物、真菌和动物共同祖先之前，是理解所有复杂生命起源的关键节点。",
    defaultExpanded: false
  },
  {
    slug: "archaeplastida",
    parentSlug: "eukaryota",
    name: "泛植物",
    latin: "Archaeplastida",
    rank: "超类群",
    kind: "clade",
    nodeOrder: 1,
    divergenceMya: 1100,
    eraSlug: "proterozoic",
    icon: "leaf",
    color: "#8fd07f",
    traits: "初级质体来自蓝藻内共生；包含红藻、绿藻和陆生植物。",
    description: "泛植物通过一次关键的蓝藻内共生获得叶绿体，把光合作用带入真核生命，后来绿藻支系登上陆地。",
    relationships: "与动物分属真核生物不同超类群；陆生植物由绿藻祖先演化而来。",
    defaultExpanded: false
  },
  {
    slug: "embryophytes",
    parentSlug: "archaeplastida",
    name: "有胚植物",
    latin: "Embryophyta",
    rank: "演化支",
    kind: "clade",
    nodeOrder: 1,
    divergenceMya: 470,
    eraSlug: "paleozoic",
    icon: "leaf",
    color: "#8fd07f",
    traits: "多细胞胚；角质层；孢子囊；适应陆地繁殖与保水。",
    description: "植物登陆改变了岩石风化、土壤形成、水循环和大气含氧量，为陆地食物网奠定基础。",
    relationships: "由淡水绿藻祖先演化而来，后续分化为苔藓、维管植物、种子植物和开花植物。",
    defaultExpanded: false
  },
  {
    slug: "tracheophytes",
    parentSlug: "embryophytes",
    name: "维管植物",
    latin: "Tracheophyta",
    rank: "演化支",
    kind: "clade",
    nodeOrder: 1,
    divergenceMya: 430,
    eraSlug: "paleozoic",
    icon: "tree-pine",
    color: "#86c77a",
    traits: "木质部与韧皮部运输水分和养分；真正的根、茎、叶逐步形成。",
    description: "维管组织让植物能够离开湿润表面、向更高处生长，陆地生态系统由此拥有垂直结构。",
    relationships: "裸蕨代表早期维管植物；石炭纪乔木森林与后来的开花植物都属于这一支。",
    defaultExpanded: false
  },
  {
    slug: "cooksonia",
    parentSlug: "tracheophytes",
    name: "裸蕨",
    latin: "Cooksonia",
    rank: "属",
    kind: "species",
    nodeOrder: 1,
    divergenceMya: 425,
    eraSlug: "paleozoic",
    organismSlug: "cooksonia",
    icon: "leaf",
    color: "#8fd07f",
    traits: "数厘米高；无叶；叉状分枝；顶端生有孢子囊。",
    description: "裸蕨是最早明确的维管植物之一，结构简单却已具备支撑和输导系统，是陆地植物扩张的重要起点。",
    relationships: "接近维管植物早期分化位置，早于大型乔木和种子植物。",
    defaultExpanded: false
  },
  {
    slug: "lycophytes",
    parentSlug: "tracheophytes",
    name: "石松植物",
    latin: "Lycopodiopsida",
    rank: "纲",
    kind: "clade",
    nodeOrder: 2,
    divergenceMya: 410,
    eraSlug: "paleozoic",
    icon: "tree-pine",
    color: "#76b86d",
    traits: "小型叶；孢子叶球；木本种类在石炭纪森林中高度可达数十米。",
    description: "石松植物曾是石炭纪沼泽森林的重要建造者，现代类群多为低矮草本，但它们保留了维管植物早期分支的特征。",
    relationships: "与真叶植物分开较早，鳞木是其已灭绝的巨型代表。",
    defaultExpanded: false
  },
  {
    slug: "lepidodendron",
    parentSlug: "lycophytes",
    name: "鳞木",
    latin: "Lepidodendron",
    rank: "属",
    kind: "species",
    nodeOrder: 1,
    divergenceMya: 320,
    eraSlug: "paleozoic",
    organismSlug: "lepidodendron",
    icon: "tree-pine",
    color: "#76b86d",
    traits: "高可达 40 米；树干覆盖叶基留下的鳞痕；顶端产生孢子叶球。",
    description: "鳞木森林繁盛于温暖潮湿的石炭纪沼泽。埋藏后的植物有机质构成了北半球大量煤炭资源。",
    relationships: "属于早期分化的石松植物，而非现代针叶树或开花植物。",
    defaultExpanded: false
  },
  {
    slug: "euphyllophytes",
    parentSlug: "tracheophytes",
    name: "真叶植物",
    latin: "Euphyllophyta",
    rank: "演化支",
    kind: "clade",
    nodeOrder: 3,
    divergenceMya: 390,
    eraSlug: "paleozoic",
    icon: "flower-2",
    color: "#95d688",
    traits: "真正的大型叶；分枝系统复杂；包括蕨类、裸子植物和被子植物。",
    description: "真叶植物通过更大的叶面积提升光合作用，在古生代以后逐渐成为陆地植被的主体。",
    relationships: "一端连接早期维管植物，另一端通向种子植物和开花植物。",
    defaultExpanded: false
  },
  {
    slug: "spermatophytes",
    parentSlug: "euphyllophytes",
    name: "种子植物",
    latin: "Spermatophyta",
    rank: "演化支",
    kind: "clade",
    nodeOrder: 1,
    divergenceMya: 365,
    eraSlug: "paleozoic",
    icon: "flower-2",
    color: "#9edf8d",
    traits: "种子保护胚；花粉传递雄配子；对干旱陆地繁殖更适应。",
    description: "种子把营养、保护和传播能力打包给下一代，使植物能摆脱外部水膜完成受精。",
    relationships: "包含裸子植物与被子植物；开花植物是其中最晚近、多样性最高的一支。",
    defaultExpanded: false
  },
  {
    slug: "angiosperms",
    parentSlug: "spermatophytes",
    name: "被子植物",
    latin: "Angiospermae",
    rank: "演化支",
    kind: "clade",
    nodeOrder: 1,
    divergenceMya: 140,
    eraSlug: "mesozoic",
    icon: "flower-2",
    color: "#a7e3a0",
    traits: "花；果实包被种子；与传粉者协同演化；维管系统高效。",
    description: "开花植物在白垩纪迅速扩张，以花吸引传粉者、以果实帮助种子传播，重塑了陆地生态。",
    relationships: "与裸子植物同属种子植物，但通过花和果实形成独特繁殖系统。",
    defaultExpanded: false
  },
  {
    slug: "angiosperm",
    parentSlug: "angiosperms",
    name: "最早的开花植物",
    latin: "Angiospermae",
    rank: "基干支系",
    kind: "species",
    nodeOrder: 1,
    divergenceMya: 130,
    eraSlug: "mesozoic",
    organismSlug: "angiosperm",
    icon: "flower-2",
    color: "#a7e3a0",
    traits: "花被；心皮；胚珠包被；昆虫传粉潜力增强。",
    description: "早期被子植物的花和果实为昆虫、鸟类和哺乳动物提供新资源，促进了复杂协同演化网络。",
    relationships: "是现代绝大多数陆生植物的祖先类群之一，与传粉昆虫的辐射相互推动。",
    defaultExpanded: false
  },
  {
    slug: "opisthokonta",
    parentSlug: "eukaryota",
    name: "后鞭毛生物",
    latin: "Opisthokonta",
    rank: "超类群",
    kind: "clade",
    nodeOrder: 2,
    divergenceMya: 1000,
    eraSlug: "proterozoic",
    icon: "bug",
    color: "#9dc8e8",
    traits: "运动细胞通常具单根后鞭毛；包括真菌和动物。",
    description: "后鞭毛生物把动物和真菌联系在同一真核分支中。它们的共同祖先可能是小型单细胞异养生物。",
    relationships: "动物与真菌的共同祖先早于多细胞身体出现，多细胞化在两个分支中独立发展。",
    defaultExpanded: true
  },
  {
    slug: "animalia",
    parentSlug: "opisthokonta",
    name: "动物",
    latin: "Animalia",
    rank: "界",
    kind: "clade",
    nodeOrder: 1,
    divergenceMya: 850,
    eraSlug: "proterozoic",
    icon: "bug",
    color: "#8fbde9",
    traits: "多细胞异养；胚胎发育；细胞外基质；多数具有神经和肌肉细胞。",
    description: "动物从简单的囊胚状多细胞生物开始，逐渐演化出对称身体、组织器官、神经系统与主动捕食能力。",
    relationships: "埃迪卡拉生物群提供早期大型动物证据，寒武纪大爆发后现代动物门类快速出现。",
    defaultExpanded: true
  },
  {
    slug: "ediacaran-biota",
    parentSlug: "animalia",
    name: "埃迪卡拉生物群",
    latin: "Ediacaran biota",
    rank: "化石群",
    kind: "clade",
    nodeOrder: 1,
    divergenceMya: 575,
    eraSlug: "proterozoic",
    icon: "disc",
    color: "#b7a8d9",
    traits: "大型软体；分叶或盘状外形；多生活在浅海床；与现代门类关系仍有争议。",
    description: "埃迪卡拉生物群是动物进入宏观世界的第一次大规模实验。它们大多没有硬壳和明显捕食附肢。",
    relationships: "部分成员可能位于现代动物分化之前，寒武纪后多数形态消失。",
    defaultExpanded: false
  },
  {
    slug: "dickinsonia",
    parentSlug: "ediacaran-biota",
    name: "狄更逊水母",
    latin: "Dickinsonia",
    rank: "属",
    kind: "species",
    nodeOrder: 1,
    divergenceMya: 575,
    eraSlug: "proterozoic",
    organismSlug: "dickinsonia",
    icon: "disc",
    color: "#b7a8d9",
    traits: "椭圆形软体；分节排列；无明显口器；可能通过体表吸收营养。",
    description: "狄更逊水母是埃迪卡拉生物群最著名的代表之一，生物标志物研究支持其与早期动物有关。",
    relationships: "代表寒武纪大爆发前的大型软体动物实验，而非现代水母的直接成员。",
    defaultExpanded: false
  },
  {
    slug: "eumetazoa",
    parentSlug: "animalia",
    name: "真后生动物",
    latin: "Eumetazoa",
    rank: "亚界",
    kind: "clade",
    nodeOrder: 2,
    divergenceMya: 650,
    eraSlug: "proterozoic",
    icon: "eye",
    color: "#7fb8e8",
    traits: "明确组织层；神经细胞；肌肉；固定体轴对称方式。",
    description: "真后生动物发展出真正的组织和神经信号，使主动运动、感知环境和捕食成为可能。",
    relationships: "包括刺胞动物、两侧对称动物等主要分支。",
    defaultExpanded: false
  },
  {
    slug: "bilateria",
    parentSlug: "eumetazoa",
    name: "两侧对称动物",
    latin: "Bilateria",
    rank: "演化支",
    kind: "clade",
    nodeOrder: 1,
    divergenceMya: 600,
    eraSlug: "proterozoic",
    icon: "git-fork",
    color: "#77aee0",
    traits: "左右对称；头尾分化；三胚层；多数具有定向运动。",
    description: "两侧对称身体让动物能够以前端感知环境、向目标移动，是捕食和复杂行为演化的重要基础。",
    relationships: "分为原口动物和后口动物两大支，前者包含节肢动物与软体动物，后者包含脊椎动物。",
    defaultExpanded: true
  },
  {
    slug: "protostomia",
    parentSlug: "bilateria",
    name: "原口动物",
    latin: "Protostomia",
    rank: "演化支",
    kind: "clade",
    nodeOrder: 1,
    divergenceMya: 580,
    eraSlug: "proterozoic",
    icon: "bug",
    color: "#72a9dc",
    traits: "胚胎发育中原肠孔先形成口；包含蜕皮动物与冠轮动物等大类。",
    description: "原口动物是动物多样性最高的分支之一，从微小蠕虫到昆虫和头足类都包含其中。",
    relationships: "与后口动物共享两侧对称祖先，但胚胎发育模式和神经系统结构沿不同路径演化。",
    defaultExpanded: false
  },
  {
    slug: "ecdysozoa",
    parentSlug: "protostomia",
    name: "蜕皮动物",
    latin: "Ecdysozoa",
    rank: "总门",
    kind: "clade",
    nodeOrder: 1,
    divergenceMya: 550,
    eraSlug: "paleozoic",
    icon: "bug",
    color: "#6ba6d8",
    traits: "周期性蜕去外骨骼；包括节肢动物、线虫等；身体分节常见。",
    description: "外骨骼提供支撑和保护，也限制身体连续增大，因此蜕皮成为这类动物成长的关键过程。",
    relationships: "三叶虫、昆虫等都属于节肢动物这一蜕皮动物分支。",
    defaultExpanded: false
  },
  {
    slug: "arthropoda",
    parentSlug: "ecdysozoa",
    name: "节肢动物",
    latin: "Arthropoda",
    rank: "门",
    kind: "clade",
    nodeOrder: 1,
    divergenceMya: 540,
    eraSlug: "paleozoic",
    icon: "bug",
    color: "#68a2d4",
    traits: "几丁质外骨骼；分节附肢；复眼；身体分区。",
    description: "节肢动物是动物界物种数量最多的门。硬壳、附肢分工和复眼让它们在寒武纪迅速占据多种生态位。",
    relationships: "奇虾、三叶虫和昆虫同属泛节肢动物大类，但具体分支位置不同。",
    defaultExpanded: false
  },
  {
    slug: "radiodonta",
    parentSlug: "arthropoda",
    name: "射齿类",
    latin: "Radiodonta",
    rank: "纲",
    kind: "clade",
    nodeOrder: 1,
    divergenceMya: 520,
    eraSlug: "paleozoic",
    icon: "eye",
    color: "#6398cf",
    traits: "大型复眼；环形口器；带刺抓握附肢；流线型游泳身体。",
    description: "射齿类是寒武纪海洋中的早期顶级捕食者，展示了动物捕食关系迅速复杂化。",
    relationships: "位于节肢动物干群附近，与现代螯肢类和甲壳类并非同一支直接延续。",
    defaultExpanded: false
  },
  {
    slug: "anomalocaris",
    parentSlug: "radiodonta",
    name: "奇虾",
    latin: "Anomalocaris",
    rank: "属",
    kind: "species",
    nodeOrder: 1,
    divergenceMya: 508,
    eraSlug: "paleozoic",
    organismSlug: "anomalocaris",
    icon: "eye",
    color: "#6398cf",
    traits: "体长可达一米；抓握附肢；巨大复眼；寒武纪顶级捕食者。",
    description: "奇虾曾被不同化石碎片误判为多种生物，完整化石揭示它是高度能动的海洋捕食者。",
    relationships: "代表节肢动物干群的早期实验，与三叶虫生活在同一寒武纪食物网。",
    defaultExpanded: false
  },
  {
    slug: "trilobitomorpha",
    parentSlug: "arthropoda",
    name: "三叶形类",
    latin: "Trilobitomorpha",
    rank: "亚门",
    kind: "clade",
    nodeOrder: 2,
    divergenceMya: 521,
    eraSlug: "paleozoic",
    icon: "bug",
    color: "#78addb",
    traits: "背甲分三叶；分节躯干；复眼；多数底栖。",
    description: "三叶形类在古生代海洋中极其繁盛，是古生代地层最重要的标准化石之一。",
    relationships: "属于早期节肢动物分支，在二叠纪末大灭绝中完全消失。",
    defaultExpanded: false
  },
  {
    slug: "trilobite",
    parentSlug: "trilobitomorpha",
    name: "三叶虫",
    latin: "Trilobita",
    rank: "纲",
    kind: "species",
    nodeOrder: 1,
    divergenceMya: 521,
    eraSlug: "paleozoic",
    organismSlug: "trilobite",
    icon: "bug",
    color: "#78addb",
    traits: "矿化背甲；轴叶与两肋叶；可蜷曲防御；复眼发达。",
    description: "三叶虫繁盛近三亿年，记录了寒武纪海洋生态和节肢动物早期演化，最终在二叠纪末灭绝。",
    relationships: "与奇虾同为古生代海洋节肢动物，但亲缘关系较远。",
    defaultExpanded: false
  },
  {
    slug: "hexapoda",
    parentSlug: "arthropoda",
    name: "六足类",
    latin: "Hexapoda",
    rank: "亚门",
    kind: "clade",
    nodeOrder: 3,
    divergenceMya: 410,
    eraSlug: "paleozoic",
    icon: "wind",
    color: "#8db8df",
    traits: "三对足；身体分头、胸、腹；多数昆虫具翅。",
    description: "六足类在陆地生态系统中占据巨大数量优势，昆虫的飞行与变态发育进一步提升适应性。",
    relationships: "登陆后与植物形成传粉、植食和分解等紧密关系；石炭纪高氧环境出现巨型飞行昆虫。",
    defaultExpanded: false
  },
  {
    slug: "meganeura",
    parentSlug: "hexapoda",
    name: "巨脉蜻蜓",
    latin: "Meganeura",
    rank: "属",
    kind: "species",
    nodeOrder: 1,
    divergenceMya: 315,
    eraSlug: "paleozoic",
    organismSlug: "meganeura",
    icon: "wind",
    color: "#8db8df",
    traits: "翼展约 70 厘米；大型复眼；飞行捕食；依赖高氧环境。",
    description: "巨脉蜻蜓是石炭纪陆地高氧生态的标志。气管呼吸效率和生态位共同限制了昆虫体型上限。",
    relationships: "属于蜻蜓近亲支系，是最早统治天空的动物之一，早于翼龙、鸟类和蝙蝠。",
    defaultExpanded: false
  },
  {
    slug: "lophotrochozoa",
    parentSlug: "protostomia",
    name: "冠轮动物",
    latin: "Lophotrochozoa",
    rank: "总门",
    kind: "clade",
    nodeOrder: 2,
    divergenceMya: 540,
    eraSlug: "paleozoic",
    icon: "snail",
    color: "#8bb3d7",
    traits: "包括软体动物、环节动物、腕足动物等；常见担轮幼虫或滤食冠。",
    description: "冠轮动物的身体计划极其多样，从缓慢爬行的螺类到敏捷聪明的头足类都在其中。",
    relationships: "菊石属于软体动物门头足类，与节肢动物同属原口动物但不是近亲。",
    defaultExpanded: false
  },
  {
    slug: "mollusca",
    parentSlug: "lophotrochozoa",
    name: "软体动物",
    latin: "Mollusca",
    rank: "门",
    kind: "clade",
    nodeOrder: 1,
    divergenceMya: 535,
    eraSlug: "paleozoic",
    icon: "snail",
    color: "#80a7d0",
    traits: "外套膜；齿舌；肌肉足；许多类群具碳酸钙外壳。",
    description: "软体动物是海洋、淡水和陆地生态中的重要类群。头足类通过神经系统、视觉和喷水运动发展出主动捕食生活。",
    relationships: "菊石与现代章鱼、乌贼、鹦鹉螺同属头足类，外壳策略在不同支系中变化。",
    defaultExpanded: false
  },
  {
    slug: "cephalopoda",
    parentSlug: "mollusca",
    name: "头足类",
    latin: "Cephalopoda",
    rank: "纲",
    kind: "clade",
    nodeOrder: 1,
    divergenceMya: 500,
    eraSlug: "paleozoic",
    icon: "snail",
    color: "#769cc9",
    traits: "触手环绕头部；发达眼和脑；喷水推进；许多化石类群具旋卷外壳。",
    description: "头足类是无脊椎动物中神经系统和行为最复杂的类群之一，在古生代和中生代海洋中非常繁盛。",
    relationships: "菊石是中生代头足类代表，在 K-Pg 大灭绝中消失；现代蛸亚纲多数外壳退化。",
    defaultExpanded: false
  },
  {
    slug: "ammonite",
    parentSlug: "cephalopoda",
    name: "菊石",
    latin: "Ammonoidea",
    rank: "亚纲",
    kind: "species",
    nodeOrder: 1,
    divergenceMya: 240,
    eraSlug: "mesozoic",
    organismSlug: "ammonite",
    icon: "snail",
    color: "#769cc9",
    traits: "螺旋分隔外壳；缝合线复杂；海洋游泳捕食者；重要指准化石。",
    description: "菊石壳内气室帮助控制浮力，外壳花纹和缝合线随类群演化迅速变化，因此常用于确定地层年代。",
    relationships: "与沧龙、鱼龙等海洋爬行动物共享中生代海洋，但属于完全不同的动物门类。",
    defaultExpanded: false
  },
  {
    slug: "deuterostomia",
    parentSlug: "bilateria",
    name: "后口动物",
    latin: "Deuterostomia",
    rank: "演化支",
    kind: "clade",
    nodeOrder: 2,
    divergenceMya: 570,
    eraSlug: "proterozoic",
    icon: "fish",
    color: "#c9b458",
    traits: "胚胎发育中原肠孔先形成肛门；包括棘皮动物和脊索动物。",
    description: "后口动物早期成员多生活在海洋中。脊索动物支系后来演化出背神经管、脊索和脊椎骨。",
    relationships: "人类与鱼类、两栖类、爬行类、鸟类和其他哺乳类都属于后口动物中的脊索动物。",
    defaultExpanded: true
  },
  {
    slug: "chordata",
    parentSlug: "deuterostomia",
    name: "脊索动物",
    latin: "Chordata",
    rank: "门",
    kind: "clade",
    nodeOrder: 1,
    divergenceMya: 530,
    eraSlug: "paleozoic",
    icon: "fish",
    color: "#6ea8e0",
    traits: "脊索；背神经管；鳃裂；肛后尾。",
    description: "脊索动物的基本身体蓝图最早出现在小型海洋动物中，后来脊椎动物将其发展为内骨骼和复杂头部。",
    relationships: "昆明鱼代表早期脊椎动物，通向所有鱼类和四足动物。",
    defaultExpanded: true
  },
  {
    slug: "vertebrata",
    parentSlug: "chordata",
    name: "脊椎动物",
    latin: "Vertebrata",
    rank: "亚门",
    kind: "clade",
    nodeOrder: 1,
    divergenceMya: 518,
    eraSlug: "paleozoic",
    icon: "fish",
    color: "#5f9ad8",
    traits: "脊椎骨；头骨；发达中枢神经；鳃或肺呼吸。",
    description: "脊椎动物以内骨骼支撑更大体型，并通过头部感官、循环系统和运动能力扩展到各种环境。",
    relationships: "从早期无颌鱼类分化出有颌鱼类，再通向四足动物。",
    defaultExpanded: true
  },
  {
    slug: "myllokunmingia",
    parentSlug: "vertebrata",
    name: "昆明鱼",
    latin: "Myllokunmingia",
    rank: "属",
    kind: "species",
    nodeOrder: 1,
    divergenceMya: 518,
    eraSlug: "paleozoic",
    organismSlug: "myllokunmingia",
    icon: "fish",
    color: "#6ea8e0",
    traits: "体长约 3 厘米；脊索；鳃弓；分节肌肉；可能具低弱鳍。",
    description: "昆明鱼是已知最早的脊椎动物候选之一，保存了脊椎动物头部和鳃区的早期结构。",
    relationships: "位于脊椎动物谱系很基部，是鱼类与后来四足动物共同蓝图的早期记录。",
    defaultExpanded: false
  },
  {
    slug: "gnathostomata",
    parentSlug: "vertebrata",
    name: "有颌类",
    latin: "Gnathostomata",
    rank: "总纲",
    kind: "clade",
    nodeOrder: 2,
    divergenceMya: 440,
    eraSlug: "paleozoic",
    icon: "fish-symbol",
    color: "#5b92cf",
    traits: "颌；成对鼻孔；成对鳍；钙化脊椎和牙齿逐渐发达。",
    description: "颌由鳃弓演化而来，使脊椎动物能主动咬合和处理更大猎物，成为海洋食物网中的强势捕食者。",
    relationships: "包括盾皮鱼、软骨鱼、硬骨鱼以及所有四足动物。",
    defaultExpanded: false
  },
  {
    slug: "placodermi",
    parentSlug: "gnathostomata",
    name: "盾皮鱼纲",
    latin: "Placodermi",
    rank: "纲",
    kind: "clade",
    nodeOrder: 1,
    divergenceMya: 430,
    eraSlug: "paleozoic",
    icon: "fish-symbol",
    color: "#6f91bd",
    traits: "头胸部覆盖骨甲；骨板形成颌刃；许多种类底栖，部分成为顶级捕食者。",
    description: "盾皮鱼是最早占据大型海洋捕食者生态位的有颌脊椎动物，泥盆纪后灭绝。",
    relationships: "展示了颌与骨甲的早期实验，邓氏鱼是其最著名代表。",
    defaultExpanded: false
  },
  {
    slug: "dunkleosteus",
    parentSlug: "placodermi",
    name: "邓氏鱼",
    latin: "Dunkleosteus",
    rank: "属",
    kind: "species",
    nodeOrder: 1,
    divergenceMya: 382,
    eraSlug: "paleozoic",
    organismSlug: "dunkleosteus",
    icon: "fish-symbol",
    color: "#6f91bd",
    traits: "体长可达 6 米；厚重骨甲；无真正牙齿而有锋利骨刃；强大咬合力。",
    description: "邓氏鱼能以骨板剪切猎物，是泥盆纪海洋顶级捕食者。其骨骼结构记录了有颌类早期演化。",
    relationships: "不是现代鲨鱼的祖先，而是已灭绝的盾皮鱼支系。",
    defaultExpanded: false
  },
  {
    slug: "osteichthyes",
    parentSlug: "gnathostomata",
    name: "硬骨鱼",
    latin: "Osteichthyes",
    rank: "高纲",
    kind: "clade",
    nodeOrder: 2,
    divergenceMya: 425,
    eraSlug: "paleozoic",
    icon: "fish",
    color: "#4f93d1",
    traits: "硬骨内骨骼；鳃盖；鳔或肺；包括辐鳍鱼和肉鳍鱼。",
    description: "硬骨鱼是脊椎动物多样性最高的支系之一。肉鳍鱼类的一支后来演化为所有陆生四足动物。",
    relationships: "提塔利克鱼位于肉鳍鱼到四足动物的过渡带。",
    defaultExpanded: true
  },
  {
    slug: "sarcopterygii",
    parentSlug: "osteichthyes",
    name: "肉鳍鱼",
    latin: "Sarcopterygii",
    rank: "纲",
    kind: "clade",
    nodeOrder: 1,
    divergenceMya: 410,
    eraSlug: "paleozoic",
    icon: "fish",
    color: "#568dbf",
    traits: "肉质叶状鳍；鳍内有中轴骨；肺呼吸能力；包括肺鱼、腔棘鱼和四足动物。",
    description: "肉鳍鱼的叶状鳍具有支撑身体的骨骼基础，浅水缺氧环境推动了肺呼吸和近岸活动。",
    relationships: "四足动物不是从现代辐鳍鱼演化，而是从古代肉鳍鱼类分支登上陆地。",
    defaultExpanded: false
  },
  {
    slug: "tetrapodomorpha",
    parentSlug: "sarcopterygii",
    name: "四足形类",
    latin: "Tetrapodomorpha",
    rank: "演化支",
    kind: "clade",
    nodeOrder: 1,
    divergenceMya: 390,
    eraSlug: "paleozoic",
    icon: "footprints",
    color: "#c4ac55",
    traits: "鳍骨趋向四肢排列；肩带与头骨分离；浅水环境运动能力增强。",
    description: "四足形类记录了从鱼形身体到四足身体的连续变化，许多过渡化石兼具鳍与四肢特征。",
    relationships: "提塔利克鱼是该支系的关键过渡，鱼石螈则已成为早期四足动物。",
    defaultExpanded: true
  },
  {
    slug: "tiktaalik",
    parentSlug: "tetrapodomorpha",
    name: "提塔利克鱼",
    latin: "Tiktaalik",
    rank: "属",
    kind: "species",
    nodeOrder: 1,
    divergenceMya: 375,
    eraSlug: "paleozoic",
    organismSlug: "tiktaalik",
    icon: "fish",
    color: "#9faf63",
    traits: "鳃与肺；可转动颈部；肉质鳍内具肱骨、桡骨和腕骨雏形。",
    description: "提塔利克鱼生活在浅水河口中，能用带骨的鳍支撑身体，是解释登陆过程的标志性过渡化石。",
    relationships: "位于肉鳍鱼与真正四足动物之间，与鱼石螈构成连续的登陆序列。",
    defaultExpanded: false
  },
  {
    slug: "tetrapoda",
    parentSlug: "tetrapodomorpha",
    name: "四足动物",
    latin: "Tetrapoda",
    rank: "总纲",
    kind: "clade",
    nodeOrder: 2,
    divergenceMya: 365,
    eraSlug: "paleozoic",
    icon: "footprints",
    color: "#c9b458",
    traits: "四肢与趾；颈部运动；听骨变化；适应空气呼吸和重力支撑。",
    description: "四足动物把鱼类的成对鳍改造为四肢，逐渐占据淡水边、湿地和内陆生境。",
    relationships: "包括两栖动物和羊膜动物；即使蛇、鲸等失去明显四肢，也仍属于四足动物谱系。",
    defaultExpanded: true
  },
  {
    slug: "ichthyostega",
    parentSlug: "tetrapoda",
    name: "鱼石螈",
    latin: "Ichthyostega",
    rank: "属",
    kind: "species",
    nodeOrder: 1,
    divergenceMya: 365,
    eraSlug: "paleozoic",
    organismSlug: "ichthyostega",
    icon: "footprints",
    color: "#c9b458",
    traits: "强壮四肢；肋骨发达；保留鱼尾和鳃相关结构；运动仍依赖水。",
    description: "鱼石螈是最早被广泛认识的早期四足动物之一，证明脊椎动物在泥盆纪已经开始登陆。",
    relationships: "由提塔利克鱼式祖先演化而来，是现代两栖类和羊膜类共同基干附近的成员。",
    defaultExpanded: false
  },
  {
    slug: "amniota",
    parentSlug: "tetrapoda",
    name: "羊膜动物",
    latin: "Amniota",
    rank: "演化支",
    kind: "clade",
    nodeOrder: 2,
    divergenceMya: 340,
    eraSlug: "paleozoic",
    icon: "turtle",
    color: "#b099f2",
    traits: "羊膜卵或胎生；防水皮肤；更高效肺呼吸；繁殖摆脱自由幼虫阶段。",
    description: "羊膜卵为胚胎提供液体环境和营养储备，使脊椎动物能够远离水域繁殖。",
    relationships: "分化为合弓纲（哺乳动物谱系）与蜥形纲（爬行动物、鸟类谱系）。",
    defaultExpanded: true
  },
  {
    slug: "synapsida",
    parentSlug: "amniota",
    name: "合弓纲",
    latin: "Synapsida",
    rank: "演化支",
    kind: "clade",
    nodeOrder: 1,
    divergenceMya: 320,
    eraSlug: "paleozoic",
    icon: "paw-print",
    color: "#e6bd73",
    traits: "头骨单颞颥孔；牙齿分化；通向哺乳类的代谢、听骨和体毛变化。",
    description: "合弓纲是羊膜动物两大分支之一，在恐龙时代以前曾出现多种大型陆生动物。",
    relationships: "林蜥属于羊膜动物早期分支附近；摩根锥齿兽和现代哺乳动物位于合弓纲内部。",
    defaultExpanded: true
  },
  {
    slug: "mammaliaformes",
    parentSlug: "synapsida",
    name: "哺乳形类",
    latin: "Mammaliaformes",
    rank: "演化支",
    kind: "clade",
    nodeOrder: 1,
    divergenceMya: 210,
    eraSlug: "mesozoic",
    icon: "paw-print",
    color: "#ddb46c",
    traits: "毛发；乳腺；三块听小骨；异型齿；较高代谢和体温调节。",
    description: "哺乳动物特征在中生代逐步组合。早期成员多为小型夜行性动物，以昆虫和种子为食。",
    relationships: "哺乳动物与爬行动物的相似鳞片并非同源；鸟类位于蜥形纲另一侧。",
    defaultExpanded: false
  },
  {
    slug: "morganucodon",
    parentSlug: "mammaliaformes",
    name: "摩根锥齿兽",
    latin: "Morganucodon",
    rank: "属",
    kind: "species",
    nodeOrder: 1,
    divergenceMya: 205,
    eraSlug: "mesozoic",
    organismSlug: "morganucodon",
    icon: "paw-print",
    color: "#e6bd73",
    traits: "鼩鼱大小；夜行；食虫；毛发与哺乳特征接近真正哺乳动物。",
    description: "摩根锥齿兽保存了哺乳动物颌骨听觉结构转变的关键证据，在恐龙时代维持小型生态位。",
    relationships: "位于哺乳动物起源附近，是后来有袋类、有胎盘类等现代哺乳动物的近亲基干。",
    defaultExpanded: false
  },
  {
    slug: "eutheria",
    parentSlug: "mammaliaformes",
    name: "有胎盘类",
    latin: "Eutheria",
    rank: "下纲",
    kind: "clade",
    nodeOrder: 2,
    divergenceMya: 100,
    eraSlug: "mesozoic",
    icon: "paw-print",
    color: "#e8c879",
    traits: "胎盘延长妊娠；幼崽出生时发育较完全；多样牙齿和社会行为。",
    description: "有胎盘类在白垩纪已经出现，K-Pg 灭绝后快速辐射，占据陆地、海洋和空中生态位。",
    relationships: "真猛犸象与智人同属有胎盘类；鲸类由陆生偶蹄类祖先重返水域。",
    defaultExpanded: false
  },
  {
    slug: "cetacea",
    parentSlug: "eutheria",
    name: "鲸偶蹄目—鲸类",
    latin: "Cetacea",
    rank: "目",
    kind: "clade",
    nodeOrder: 1,
    divergenceMya: 50,
    eraSlug: "cenozoic",
    icon: "waves",
    color: "#9dc6d8",
    traits: "身体流线型；前肢成鳍；尾水平分叶；听觉和潜水能力高度特化。",
    description: "鲸类由小型陆生偶蹄动物逐步重返海洋，四肢、呼吸和感官都经历深度改造。",
    relationships: "龙王鲸保存了仍可见的小型后肢，是重返水域的重要化石证据。",
    defaultExpanded: false
  },
  {
    slug: "basilosaurus",
    parentSlug: "cetacea",
    name: "龙王鲸",
    latin: "Basilosaurus",
    rank: "属",
    kind: "species",
    nodeOrder: 1,
    divergenceMya: 38,
    eraSlug: "cenozoic",
    organismSlug: "basilosaurus",
    icon: "waves",
    color: "#9dc6d8",
    traits: "身体细长可达 18 米；残留后肢；完全海生；牙齿仍较分化。",
    description: "龙王鲸是早期大型鲸类，其髋骨和后肢残留证明鲸类祖先曾在陆地行走。",
    relationships: "属于哺乳动物重返海洋的分支，与沧龙等海洋爬行动物只是生态相似而非近亲。",
    defaultExpanded: false
  },
  {
    slug: "proboscidea",
    parentSlug: "eutheria",
    name: "长鼻目",
    latin: "Proboscidea",
    rank: "目",
    kind: "clade",
    nodeOrder: 2,
    divergenceMya: 60,
    eraSlug: "cenozoic",
    icon: "snowflake",
    color: "#d8c4a1",
    traits: "长鼻；发达象牙；大体型；复杂社会学习。",
    description: "长鼻目曾在多个大陆分化出许多类群，真猛犸象适应寒冷草原并与早期人类长期共存。",
    relationships: "真猛犸象与现代亚洲象亲缘较近，属于新生代哺乳动物辐射的一部分。",
    defaultExpanded: false
  },
  {
    slug: "mammoth",
    parentSlug: "proboscidea",
    name: "真猛犸象",
    latin: "Mammuthus primigenius",
    rank: "种",
    kind: "species",
    nodeOrder: 1,
    divergenceMya: 0.4,
    eraSlug: "cenozoic",
    organismSlug: "mammoth",
    icon: "snowflake",
    color: "#d8c4a1",
    traits: "长毛；厚脂肪；弯曲长牙；适应寒冷草原；与人类活动时间重叠。",
    description: "真猛犸象在更新世冰原上广泛分布，气候变化和人类捕猎可能共同导致其种群衰退。",
    relationships: "是现代象科近亲，不是恐龙时代的动物，而属于新生代哺乳动物。",
    defaultExpanded: false
  },
  {
    slug: "primates",
    parentSlug: "eutheria",
    name: "灵长目",
    latin: "Primates",
    rank: "目",
    kind: "clade",
    nodeOrder: 3,
    divergenceMya: 65,
    eraSlug: "cenozoic",
    icon: "brain",
    color: "#f2f2e8",
    traits: "前向立体视觉；抓握手；扩大脑区；社会学习增强。",
    description: "灵长类在树冠环境中发展出灵活手指、立体视觉和复杂社会关系，其中人族支系后来直立行走。",
    relationships: "南方古猿、直立人与智人同属人族支系，与黑猩猩分支在非洲分离。",
    defaultExpanded: true
  },
  {
    slug: "hominini",
    parentSlug: "primates",
    name: "人族",
    latin: "Hominini",
    rank: "族",
    kind: "clade",
    nodeOrder: 1,
    divergenceMya: 6.5,
    eraSlug: "cenozoic",
    icon: "footprints",
    color: "#e9e4cf",
    traits: "习惯性直立行走；骨盆与脊柱重塑；脑容量后期显著增大。",
    description: "人族在非洲与黑猩猩支系分开。直立行走先于大脑扩张，改变了移动、觅食和工具使用方式。",
    relationships: "南方古猿接近早期人族阶段，人属随后在工具、火和迁徙方面发生显著变化。",
    defaultExpanded: true
  },
  {
    slug: "australopithecus",
    parentSlug: "hominini",
    name: "南方古猿",
    latin: "Australopithecus",
    rank: "属",
    kind: "species",
    nodeOrder: 1,
    divergenceMya: 3.9,
    eraSlug: "cenozoic",
    organismSlug: "australopithecus",
    icon: "footprints",
    color: "#e6d7b7",
    traits: "习惯性双足行走；脑容量接近黑猩猩；树栖适应仍部分保留。",
    description: "“露西”等化石表明南方古猿已经以双足在稀树草原移动，但智力和工具文化尚未达到后来人属水平。",
    relationships: "可能位于通向人属的祖先群附近，是直立行走先于脑扩张的证据。",
    defaultExpanded: false
  },
  {
    slug: "homo",
    parentSlug: "hominini",
    name: "人属",
    latin: "Homo",
    rank: "属",
    kind: "clade",
    nodeOrder: 2,
    divergenceMya: 2.4,
    eraSlug: "cenozoic",
    icon: "flame",
    color: "#f0ead6",
    traits: "石器；用火；长途迁徙；脑容量增加；合作与文化传承。",
    description: "人属通过工具、火、社会协作和文化学习改变适应方式，不再只依赖身体结构演化。",
    relationships: "直立人较早走出非洲，智人则在非洲起源后扩散全球。",
    defaultExpanded: true
  },
  {
    slug: "homo-erectus",
    parentSlug: "homo",
    name: "直立人",
    latin: "Homo erectus",
    rank: "种",
    kind: "species",
    nodeOrder: 1,
    divergenceMya: 1.9,
    eraSlug: "cenozoic",
    organismSlug: "homo-erectus",
    icon: "flame",
    color: "#ead9b7",
    traits: "完全直立；阿舍利石器；使用火；最早广泛走出非洲的人属物种。",
    description: "直立人在非洲和欧亚大陆生存近二百万年，火的使用改善食物、防御和社会活动。",
    relationships: "位于南方古猿之后、智人之前，是人属身体比例和迁徙能力现代化的重要阶段。",
    defaultExpanded: false
  },
  {
    slug: "homo-sapiens",
    parentSlug: "homo",
    name: "智人",
    latin: "Homo sapiens",
    rank: "种",
    kind: "species",
    nodeOrder: 2,
    divergenceMya: 0.3,
    eraSlug: "cenozoic",
    organismSlug: "homo-sapiens",
    icon: "brain",
    color: "#f2f2e8",
    traits: "符号语言；复杂工具；艺术与抽象思维；全球迁徙；文化演化迅速。",
    description: "智人约 30 万年前在非洲出现，随后扩散到全球。语言、合作和想象共同体使知识能跨代累积。",
    relationships: "属于灵长目、人属；与尼安德特人等近亲曾共存，当前所有人类属于同一物种。",
    defaultExpanded: false
  },
  {
    slug: "sauropsida",
    parentSlug: "amniota",
    name: "蜥形纲",
    latin: "Sauropsida",
    rank: "演化支",
    kind: "clade",
    nodeOrder: 2,
    divergenceMya: 320,
    eraSlug: "paleozoic",
    icon: "turtle",
    color: "#b099f2",
    traits: "鳞片角蛋白化；羊膜卵；多样肺呼吸；包括传统爬行类和鸟类。",
    description: "蜥形纲是羊膜动物另一大分支。早期小型爬行动物在古生代晚期出现，中生代演化出恐龙、翼龙和海洋爬行动物。",
    relationships: "林蜥接近早期羊膜动物位置；鸟类属于蜥形纲中的兽脚类恐龙，而不是独立于恐龙之外。",
    defaultExpanded: true
  },
  {
    slug: "hylonomus",
    parentSlug: "sauropsida",
    name: "林蜥",
    latin: "Hylonomus",
    rank: "属",
    kind: "species",
    nodeOrder: 1,
    divergenceMya: 312,
    eraSlug: "paleozoic",
    organismSlug: "hylonomus",
    icon: "turtle",
    color: "#a890db",
    traits: "约 20 厘米；轻巧四肢；食虫；羊膜卵；早期陆生羊膜动物。",
    description: "林蜥化石常发现于石炭纪树桩沉积中，代表羊膜动物早期向内陆森林扩张的阶段。",
    relationships: "位于合弓纲与蜥形纲分化附近，展示羊膜卵出现后的早期适应。",
    defaultExpanded: false
  },
  {
    slug: "archosauria",
    parentSlug: "sauropsida",
    name: "主龙类",
    latin: "Archosauria",
    rank: "演化支",
    kind: "clade",
    nodeOrder: 2,
    divergenceMya: 250,
    eraSlug: "mesozoic",
    icon: "bone",
    color: "#ec8c78",
    traits: "头骨开孔；直立或半直立四肢；包括鳄形类、翼龙和恐龙。",
    description: "三叠纪大灭绝后主龙类接管许多陆地生态位，恐龙成为中生代最醒目的陆地脊椎动物。",
    relationships: "翼龙是恐龙近亲但不是恐龙；鸟类则直接位于恐龙内部。",
    defaultExpanded: true
  },
  {
    slug: "pterosauria",
    parentSlug: "archosauria",
    name: "翼龙目",
    latin: "Pterosauria",
    rank: "目",
    kind: "clade",
    nodeOrder: 1,
    divergenceMya: 228,
    eraSlug: "mesozoic",
    icon: "feather",
    color: "#c79ad8",
    traits: "延长第四指支撑翼膜；中空骨骼；飞行；部分具头冠。",
    description: "翼龙是第一群主动飞行的脊椎动物，体型从小型昆虫捕食者到小型飞机大小的大型种类。",
    relationships: "与恐龙同属主龙类，但翼膜结构不同于鸟类羽毛翅膀。",
    defaultExpanded: false
  },
  {
    slug: "pteranodon",
    parentSlug: "pterosauria",
    name: "无齿翼龙",
    latin: "Pteranodon",
    rank: "属",
    kind: "species",
    nodeOrder: 1,
    divergenceMya: 85,
    eraSlug: "mesozoic",
    organismSlug: "pteranodon",
    icon: "feather",
    color: "#c79ad8",
    traits: "翼展可达 7 米；无齿；大型头冠；海洋上空滑翔捕食鱼类。",
    description: "无齿翼龙展示翼龙对海洋上空生态位的适应，其骨骼轻量化和翼膜支持高效滑翔。",
    relationships: "不是鸟类祖先；真正鸟类由兽脚类恐龙的羽毛翅膀独立演化飞行结构。",
    defaultExpanded: false
  },
  {
    slug: "dinosauria",
    parentSlug: "archosauria",
    name: "恐龙总目",
    latin: "Dinosauria",
    rank: "总目",
    kind: "clade",
    nodeOrder: 2,
    divergenceMya: 233,
    eraSlug: "mesozoic",
    icon: "bone",
    color: "#ec8c78",
    traits: "直立四肢；髋臼开孔；鸟颈类和蜥臀类两大支；羽毛在许多支系中出现。",
    description: "恐龙在三叠纪晚期出现并统治陆地生态系统超过一亿六千万年。现代鸟类是仍存活的兽脚类恐龙。",
    relationships: "梁龙、剑龙、霸王龙和始祖鸟都在恐龙谱系内部；沧龙和翼龙不属于恐龙。",
    defaultExpanded: true
  },
  {
    slug: "sauropodomorpha",
    parentSlug: "dinosauria",
    name: "蜥脚形亚目",
    latin: "Sauropodomorpha",
    rank: "亚目",
    kind: "clade",
    nodeOrder: 1,
    divergenceMya: 230,
    eraSlug: "mesozoic",
    icon: "bone",
    color: "#d9917d",
    traits: "长颈长尾；柱状四肢；植食；巨型化；小头部与广泛取食范围。",
    description: "蜥脚类是地球历史上最大的陆地动物之一，通过长颈和高效消化处理大量植物。",
    relationships: "梁龙是其代表，与鸟类所在的兽脚类亲缘关系较远。",
    defaultExpanded: false
  },
  {
    slug: "diplodocus",
    parentSlug: "sauropodomorpha",
    name: "梁龙",
    latin: "Diplodocus",
    rank: "属",
    kind: "species",
    nodeOrder: 1,
    divergenceMya: 154,
    eraSlug: "mesozoic",
    organismSlug: "diplodocus",
    icon: "bone",
    color: "#d9917d",
    traits: "体长超过 25 米；鞭状长尾；钉状齿；低位置取食蕨类和嫩枝。",
    description: "梁龙拥有极长颈部和尾部，代表侏罗纪蜥脚类在体型上的极端演化。",
    relationships: "属于蜥臀类中的蜥脚形亚目，不是三角龙等鸟臀类恐龙的近亲。",
    defaultExpanded: false
  },
  {
    slug: "ornithischia",
    parentSlug: "dinosauria",
    name: "鸟臀目",
    latin: "Ornithischia",
    rank: "目",
    kind: "clade",
    nodeOrder: 2,
    divergenceMya: 225,
    eraSlug: "mesozoic",
    icon: "bone",
    color: "#e2a56f",
    traits: "盆骨类似鸟类排列；植食；喙；多样防御结构如骨板、角和颈盾。",
    description: "鸟臀类发展出角、甲、骨板和群体防御等多样适应，是白垩纪陆地植物取食者的重要组成。",
    relationships: "鸟臀目的“鸟臀”是趋同结构；现代鸟类实际起源于蜥臀目中的兽脚类。",
    defaultExpanded: false
  },
  {
    slug: "stegosauria",
    parentSlug: "ornithischia",
    name: "剑龙亚目",
    latin: "Stegosauria",
    rank: "亚目",
    kind: "clade",
    nodeOrder: 1,
    divergenceMya: 170,
    eraSlug: "mesozoic",
    icon: "bone",
    color: "#dba15e",
    traits: "背部骨板；尾刺；小头；植食；可能使用展示和体温调节。",
    description: "剑龙类以背部交错骨板和尾刺著称，骨板功能包括展示、防御或热调节等多种假说。",
    relationships: "与后期的三角龙同属鸟臀目，但分属不同分支。",
    defaultExpanded: false
  },
  {
    slug: "stegosaurus",
    parentSlug: "stegosauria",
    name: "剑龙",
    latin: "Stegosaurus",
    rank: "属",
    kind: "species",
    nodeOrder: 1,
    divergenceMya: 155,
    eraSlug: "mesozoic",
    organismSlug: "stegosaurus",
    icon: "bone",
    color: "#dba15e",
    traits: "两排骨板；尾端四刺；脑相对体型很小；侏罗纪植食者。",
    description: "剑龙的骨板可能有血管网络用于体温调节，也可能在同类识别和展示中发挥作用。",
    relationships: "是鸟臀目剑龙类代表，早于白垩纪晚期的霸王龙和三角龙。",
    defaultExpanded: false
  },
  {
    slug: "ceratopsia",
    parentSlug: "ornithischia",
    name: "角龙亚目",
    latin: "Ceratopsia",
    rank: "亚目",
    kind: "clade",
    nodeOrder: 2,
    divergenceMya: 160,
    eraSlug: "mesozoic",
    icon: "bone",
    color: "#e59c72",
    traits: "角质喙；面部角；颈盾；植食；许多种类群居。",
    description: "角龙类在白垩纪亚洲和北美繁盛，角与颈盾可用于防御、展示和种内竞争。",
    relationships: "三角龙与霸王龙生活在同一生态系统，但属于鸟臀目植食恐龙。",
    defaultExpanded: false
  },
  {
    slug: "triceratops",
    parentSlug: "ceratopsia",
    name: "三角龙",
    latin: "Triceratops",
    rank: "属",
    kind: "species",
    nodeOrder: 1,
    divergenceMya: 67,
    eraSlug: "mesozoic",
    organismSlug: "triceratops",
    icon: "bone",
    color: "#e59c72",
    traits: "三只角；巨大颈盾；四足行走；体重可达数吨。",
    description: "三角龙是白垩纪末期北美最常见的大型植食恐龙之一，也是最后一批非鸟恐龙。",
    relationships: "与霸王龙同时代，是 K-Pg 灭绝前恐龙生态系统的最后成员。",
    defaultExpanded: false
  },
  {
    slug: "theropoda",
    parentSlug: "dinosauria",
    name: "兽脚亚目",
    latin: "Theropoda",
    rank: "亚目",
    kind: "clade",
    nodeOrder: 3,
    divergenceMya: 230,
    eraSlug: "mesozoic",
    icon: "feather",
    color: "#ec806f",
    traits: "多为双足；中空骨；三趾行走；羽毛广泛存在；包括所有现代鸟类。",
    description: "兽脚类从小型食肉祖先演化出庞大规模与飞行支系，羽毛并非只属于鸟类。",
    relationships: "霸王龙是大型非鸟兽脚类，始祖鸟和现代鸟类位于同一分支内部。",
    defaultExpanded: true
  },
  {
    slug: "tyrannosaurus",
    parentSlug: "theropoda",
    name: "霸王龙",
    latin: "Tyrannosaurus rex",
    rank: "种",
    kind: "species",
    nodeOrder: 1,
    divergenceMya: 68,
    eraSlug: "mesozoic",
    organismSlug: "tyrannosaurus",
    icon: "bone",
    color: "#ec806f",
    traits: "体长约 12 米；巨大头骨；强咬合力；短小两指前肢；敏锐感官。",
    description: "霸王龙是白垩纪末期北美陆地生态系统的顶级捕食者，鸟类是它在恐龙谱系中仍存活的远亲。",
    relationships: "属于兽脚类恐龙，与三角龙同时代，在 K-Pg 大灭绝中作为非鸟恐龙消失。",
    defaultExpanded: false
  },
  {
    slug: "paraves",
    parentSlug: "theropoda",
    name: "近鸟类",
    latin: "Paraves",
    rank: "演化支",
    kind: "clade",
    nodeOrder: 2,
    divergenceMya: 170,
    eraSlug: "mesozoic",
    icon: "feather",
    color: "#e59bc8",
    traits: "不对称飞羽；前臂延长；骨骼轻量化；扑翼或滑翔能力逐步增强。",
    description: "近鸟类包含驰龙类、伤齿龙类和鸟类。羽毛最初可用于保温、展示和奔跑辅助，飞行能力后来逐步完善。",
    relationships: "始祖鸟位于恐龙与鸟类过渡位置，现代鸟类不是从恐龙“变成”，而本身就是恐龙。",
    defaultExpanded: true
  },
  {
    slug: "avialae",
    parentSlug: "paraves",
    name: "鸟翼类",
    latin: "Avialae",
    rank: "演化支",
    kind: "clade",
    nodeOrder: 1,
    divergenceMya: 150,
    eraSlug: "mesozoic",
    icon: "bird",
    color: "#e59bc8",
    traits: "飞行羽；融合尾和手部骨骼；高效呼吸；角质无齿喙在后期鸟类中出现。",
    description: "鸟翼类把兽脚类的羽毛、温血和轻巧骨骼改造为飞行适应，并在大灭绝后继续快速分化。",
    relationships: "始祖鸟保留牙齿、爪和骨质尾巴，是鸟类起源的经典过渡化石。",
    defaultExpanded: true
  },
  {
    slug: "archaeopteryx",
    parentSlug: "avialae",
    name: "始祖鸟",
    latin: "Archaeopteryx",
    rank: "属",
    kind: "species",
    nodeOrder: 1,
    divergenceMya: 150,
    eraSlug: "mesozoic",
    organismSlug: "archaeopteryx",
    icon: "bird",
    color: "#e59bc8",
    traits: "飞羽和翅膀；牙齿；指爪；骨质长尾；骨骼兼具恐龙和鸟类特征。",
    description: "始祖鸟兼具爬行动物骨骼和鸟类羽毛，自发现以来就是支持演化与过渡形态的经典证据。",
    relationships: "位于鸟翼类基部附近，证明鸟类起源于兽脚类恐龙。",
    defaultExpanded: false
  },
  {
    slug: "mosasauria",
    parentSlug: "sauropsida",
    name: "沧龙科",
    latin: "Mosasauridae",
    rank: "科",
    kind: "clade",
    nodeOrder: 3,
    divergenceMya: 90,
    eraSlug: "mesozoic",
    icon: "waves",
    color: "#9f91cc",
    traits: "海生；四肢成鳍状；尾部推进；双铰接颌；由陆生有鳞类重返水域。",
    description: "沧龙类在白垩纪晚期迅速大型化，成为海洋顶级捕食者之一。",
    relationships: "沧龙属于有鳞类近亲，不是恐龙，也不是鱼龙或鲸类。",
    defaultExpanded: false
  },
  {
    slug: "mosasaurus",
    parentSlug: "mosasauria",
    name: "沧龙",
    latin: "Mosasaurus",
    rank: "属",
    kind: "species",
    nodeOrder: 1,
    divergenceMya: 75,
    eraSlug: "mesozoic",
    organismSlug: "mosasaurus",
    icon: "waves",
    color: "#9f91cc",
    traits: "体长超过 15 米；鳍状四肢；强力颌部；白垩纪海洋顶级捕食者。",
    description: "沧龙在浅海中捕食鱼类、菊石和其他海洋爬行动物，是白垩纪末期海洋食物链顶端。",
    relationships: "与现代巨蜥和蛇的亲缘关系比与恐龙、鲸类更近。",
    defaultExpanded: false
  }
];
